<?php 
$cellsCoordinates = array(
	array(
		'startCoordinateX'=>0,
		'startCoordinateY'=>0,
		'finishCoordinateX'=>1,
		'finishCoordinateY'=>1),
	array(
		'startCoordinateX'=>1,
		'startCoordinateY'=>0,
		'finishCoordinateX'=>2,
		'finishCoordinateY'=>1),
	array(
		'startCoordinateX'=>2,
		'startCoordinateY'=>0,
		'finishCoordinateX'=>3,
		'finishCoordinateY'=>1),
	array(
		'startCoordinateX'=>0,
		'startCoordinateY'=>1,
		'finishCoordinateX'=>1,
		'finishCoordinateY'=>2),
	array(
		'startCoordinateX'=>1,
		'startCoordinateY'=>1,
		'finishCoordinateX'=>2,
		'finishCoordinateY'=>2),
	array(
		'startCoordinateX'=>2,
		'startCoordinateY'=>1,
		'finishCoordinateX'=>3,
		'finishCoordinateY'=>2),
	array(
		'startCoordinateX'=>0,
		'startCoordinateY'=>2,
		'finishCoordinateX'=>1,
		'finishCoordinateY'=>3),
	array(
		'startCoordinateX'=>1,
		'startCoordinateY'=>2,
		'finishCoordinateX'=>2,
		'finishCoordinateY'=>3),
	array(
		'startCoordinateX'=>2,
		'startCoordinateY'=>2,
		'finishCoordinateX'=>3,
		'finishCoordinateY'=>3));